# Generated by Django 4.2.6 on 2023-10-11 16:20

import django.db.models.manager
import markdownfield.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', markdownfield.models.MarkdownField(rendered_field='description_rendered')),
                ('description_rendered', markdownfield.models.RenderedMarkdownField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft',
                                            max_length=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                         through='taggit.TaggedItem', to='taggit.Tag',
                                                         verbose_name='Tags')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ('-created_at',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
